server:
  port: 8400

logging:
  config: classpath:logback.xml


cc-job:
  job:
    admin:
      ### datax admin address list, such as "http://address" or "http://address01,http://address02"
      #addresses: http://127.0.0.1:8080
      addresses: http://127.0.0.1:8989/xxl-job-admin,http://127.0.0.1:8990/xxl-job-admin
    executor:
      appname: cc-job-executor
      address:
      ip:
      #port: 9999
      port: 12000
      ### job log path
      #logpath: ./data/applogs/executor/jobhandler
      logpath: /Users/zhaowenpeng/logs
      ### job log retention days
      logretentiondays: 30
    ### job, access token
    accessToken: default_token

  executor:
    #jsonpath: D:\\temp\\executor\\json\\
    jsonpath:  /Users/zhaowenpeng/Downloads/datax/

  #pypath: F:\tools\datax\bin\datax.py
  pypath: /Users/zhaowenpeng/Downloads/datax/bin/datax.py