# CC-Job 任务组编排执行器配置

spring:
  application:
    name: cc-job-executor-compose
  profiles:
      active: dev

# Actuator 配置（健康检查）
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
